//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: nft_explorer.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate `NftExplorerProto_NFTExplorerClient`, then call methods of this protocol to make API calls.
public protocol NftExplorerProto_NFTExplorerClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: NftExplorerProto_NFTExplorerClientInterceptorFactoryProtocol? { get }

  func listOwnedArtworks(
    _ request: NftExplorerProto_Account,
    callOptions: CallOptions?,
    handler: @escaping (NftExplorerProto_Artwork) -> Void
  ) -> ServerStreamingCall<NftExplorerProto_Account, NftExplorerProto_Artwork>
}

extension NftExplorerProto_NFTExplorerClientProtocol {
  public var serviceName: String {
    return "nft_explorer_proto.NFTExplorer"
  }

  /// Obtain the artworks owned by a given account.
  ///
  /// - Parameters:
  ///   - request: Request to send to ListOwnedArtworks.
  ///   - callOptions: Call options.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ServerStreamingCall` with futures for the metadata and status.
  public func listOwnedArtworks(
    _ request: NftExplorerProto_Account,
    callOptions: CallOptions? = nil,
    handler: @escaping (NftExplorerProto_Artwork) -> Void
  ) -> ServerStreamingCall<NftExplorerProto_Account, NftExplorerProto_Artwork> {
    return self.makeServerStreamingCall(
      path: "/nft_explorer_proto.NFTExplorer/ListOwnedArtworks",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListOwnedArtworksInterceptors() ?? [],
      handler: handler
    )
  }
}

public protocol NftExplorerProto_NFTExplorerClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'listOwnedArtworks'.
  func makeListOwnedArtworksInterceptors() -> [ClientInterceptor<NftExplorerProto_Account, NftExplorerProto_Artwork>]
}

public final class NftExplorerProto_NFTExplorerClient: NftExplorerProto_NFTExplorerClientProtocol {
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: NftExplorerProto_NFTExplorerClientInterceptorFactoryProtocol?

  /// Creates a client for the nft_explorer_proto.NFTExplorer service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: NftExplorerProto_NFTExplorerClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

